### ISSUE TITLE
Issues when training with MANO

### ISSUE THREAD

**Issue by anonymous-pusher** [korrawe/harp#3]
Hello I tried running the optimization using the hand template of mano instead of the arm template. For this, I mainly set use_arm to False in config_utils.py. I ran the optimization on the provided precessed sequences. I found some issues during the optimization, that are mostly related to visualization:
- Throughout all the three stages of training, the hands are only shown in some of the 9 figures. This is the case, for the ones used for training, I get like 3 out of 9. It seems like they are not in the frame. For validation, all 9 hands are there, but they are not centered, and fall on the right side of the frame. This is the case for rendered, silhouette, and loss images.
![training rendering example](https://github.com/korrawe/harp/assets/91318638/704c05bb-b28b-4690-a640-f8ba7ab75b70)
![training silhouette](https://github.com/korrawe/harp/assets/91318638/c2a022fc-e3bd-4f8d-8e73-a59ad33e2673)
![validation example](https://github.com/korrawe/harp/assets/91318638/33bbb3c2-c507-496f-8e3a-e7e615ac6db6)
- The normal maps are not updated and for the whole training I get a full purple image.
![normal_0220](https://github.com/korrawe/harp/assets/91318638/f0628b3d-3ae0-4c11-9dc3-a35a91606ba6)
- This problem is not present for the rendering done at the end of training, except for some of the images in rendered_after_opt that have similar issues regarding the misalignment of hands.
![end of training](https://github.com/korrawe/harp/assets/91318638/3444c08e-08ed-41c8-bec2-11ec746ba02a)
I wonder if these issues are only related to visualization because the resulting hand at the end of training contains some artifacts, especially on the regions between fingers.
![Example of artifacts after training](https://github.com/korrawe/harp/assets/91318638/a8f6881c-78a9-4c4e-8b4e-78c952c2cf61)

Here are the evaluation results I got from running on the sequences:
Silhouette IoU: 0.21830
 L1: 0.03951
 LPIPS: 0.22118
 MS_SSIM: 0.74872

**Comment by korrawe** [comment]
Hi mJones00,
There are two separate issues here. 
The first one is the hand not being at the center. The visualization code is correct.
The problem is the parameters in the sample sequence are for the hand model with arm, which will not work with the model w/ arm. Both models take in vectors of the same type and shape, but because the pose spaces are different, they will not match (they will fail silently). This results in the initialization not matching the silhouette, and after optimization, they could be pushed out of the frame, which is why you see the empty figures.

I updated the model with arm in the other issue so if you run it with the arm model, it should work now.
To switch between models w/ and w/o arm, we need to do the fitting again. I will provide the code for this as part of "running on new video" soon (hopefully tomorrow)

For the clean normal map, the result is not unexpected with the given set of hyperparameters. This is a trade-off between albedo regularization and normal map regularization. With so little data, it is very easy for the optimization to bake all the details into the albedo which will result in a clean normal map. This can be mitigated by increasing the albedo regularization weight and average window size ("std" in the [code](https://github.com/korrawe/harp/blob/master/optimize_sequence.py#L552)) and lowering the regularization for the normal map. The optimal hyperparameters do change depending on the sequence.

Best,
Korrawe
