### ISSUE TITLE
Will the Hand Appearance Dataset and Synthetic Dataset be made publicly available?

### ISSUE THREAD

**Issue by delaprada** [korrawe/harp#4]
Hi, thank you for providing such a good work! It has provided me with valuable insights.

May I ask if the hand appearance dataset and synthetic dataset will be made publicly available? Or if it would be possible to make the code for generating the synthetic dataset using Blender and Nimble available to the public?

Thank you very much!

**Comment by korrawe** [comment]
Hi, I added the additional data which includes subject 1 from the dataset and 4 different appearance variations that we used in the supplementary. Sequences from other subjects might take some time due to privacy issues.

We did not plan to release the synthetic dataset from NIMBLE as we did not have the licenses for them.
To render the synthetic dataset, we used the provided Blender environment (`assets/render.blend`) from [NIMBLE](https://github.com/reyuwei/NIMBLE_model/tree/main) and render them manually with some modifications on lighting and environment map. You can manually edit the albedo sampled from NIMBLE directly before rendering in Blender.
We provide the code for fitting NIMBLE to the hand surface vertex [here](https://github.com/korrawe/harp/blob/master/metro_modifications/hand_utils.py#L244). You can use these poses to synthesize new synthetic datasets with sampled/edited appearances from NIMBLE. To export mesh sequences for Blender, you can use a plugin like (Stop-motion-OBJ)[https://github.com/neverhood311/Stop-motion-OBJ].
Although, you might need some familiarity with NIMBLE and Blender.

Best,

**Comment by delaprada** [comment]
Thanks a lot!
